title: Mario Chamorro
url: "https://www.mariochamorro.com"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Template by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
#  - name: "Resume"
#    link: "https://drive.google.com/file/d/1NdyjLS31lb9tkR0btO1BbjkFN07MJQj9/view?usp=sharing"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/mariochamorroacosta/"
